-- MySQL Script generated by MySQL Workbench
-- Tue Sep  5 16:02:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dulceria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dulceria` ;

-- -----------------------------------------------------
-- Schema dulceria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dulceria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dulceria` ;

-- -----------------------------------------------------
-- Table `dulceria`.`estados_carrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria`.`estados_carrito` ;

CREATE TABLE IF NOT EXISTS `dulceria`.`estados_carrito` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dulceria`.`carritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria`.`carritos` ;

CREATE TABLE IF NOT EXISTS `dulceria`.`carritos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `precio_total` VARCHAR(45) NULL DEFAULT NULL,
  `catalogo_estado_carrito_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_carritos_catalogo_estado_carrito1`
    FOREIGN KEY (`catalogo_estado_carrito_id`)
    REFERENCES `dulceria`.`estados_carrito` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_carritos_catalogo_estado_carrito1_idx` ON `dulceria`.`carritos` (`catalogo_estado_carrito_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dulceria`.`marcas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria`.`marcas` ;

CREATE TABLE IF NOT EXISTS `dulceria`.`marcas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dulceria`.`presentaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria`.`presentaciones` ;

CREATE TABLE IF NOT EXISTS `dulceria`.`presentaciones` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dulceria`.`dulces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria`.`dulces` ;

CREATE TABLE IF NOT EXISTS `dulceria`.`dulces` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `marca_id` BIGINT NOT NULL,
  `precio` INT NOT NULL,
  `peso` FLOAT NOT NULL,
  `unidades` INT NOT NULL,
  `presentacion_id` BIGINT NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `imagen` BLOB NULL DEFAULT NULL,
  `fecha_vencimiento` DATETIME NOT NULL,
  `fecha_expedicion` DATETIME NOT NULL,
  `disponibles` INT NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_dulces_marcas1`
    FOREIGN KEY (`marca_id`)
    REFERENCES `dulceria`.`marcas` (`id`),
  CONSTRAINT `fk_dulces_presentaciones1`
    FOREIGN KEY (`presentacion_id`)
    REFERENCES `dulceria`.`presentaciones` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `codigo_UNIQUE` ON `dulceria`.`dulces` (`codigo` ASC) VISIBLE;

CREATE INDEX `fk_dulces_marcas1_idx` ON `dulceria`.`dulces` (`marca_id` ASC) VISIBLE;

CREATE INDEX `fk_dulces_presentaciones1_idx` ON `dulceria`.`dulces` (`presentacion_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dulceria`.`carritos_dulces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria`.`carritos_dulces` ;

CREATE TABLE IF NOT EXISTS `dulceria`.`carritos_dulces` (
  `carritos_id` BIGINT NOT NULL,
  `dulces_id` BIGINT NOT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `subtotal` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_carritos_has_dulces_carritos1`
    FOREIGN KEY (`carritos_id`)
    REFERENCES `dulceria`.`carritos` (`id`),
  CONSTRAINT `fk_carritos_has_dulces_dulces1`
    FOREIGN KEY (`dulces_id`)
    REFERENCES `dulceria`.`dulces` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_carritos_has_dulces_dulces1_idx` ON `dulceria`.`carritos_dulces` (`dulces_id` ASC) VISIBLE;

CREATE INDEX `fk_carritos_has_dulces_carritos1_idx` ON `dulceria`.`carritos_dulces` (`carritos_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dulceria`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria`.`categorias` ;

CREATE TABLE IF NOT EXISTS `dulceria`.`categorias` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dulceria`.`categorias_dulces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria`.`categorias_dulces` ;

CREATE TABLE IF NOT EXISTS `dulceria`.`categorias_dulces` (
  `dulces` BIGINT NOT NULL,
  `categorias_id` BIGINT NOT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_dulces_has_categorias_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `dulceria`.`categorias` (`id`),
  CONSTRAINT `fk_dulces_has_categorias_dulces`
    FOREIGN KEY (`dulces`)
    REFERENCES `dulceria`.`dulces` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_dulces_has_categorias_categorias1_idx` ON `dulceria`.`categorias_dulces` (`categorias_id` ASC) VISIBLE;

CREATE INDEX `fk_dulces_has_categorias_dulces_idx` ON `dulceria`.`categorias_dulces` (`dulces` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dulceria`.`medios_de_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria`.`medios_de_pago` ;

CREATE TABLE IF NOT EXISTS `dulceria`.`medios_de_pago` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dulceria`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dulceria`.`ventas` ;

CREATE TABLE IF NOT EXISTS `dulceria`.`ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `precio_total` INT NOT NULL,
  `medios_de_pago_id` BIGINT NOT NULL,
  `carritos_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ventas_carritos1`
    FOREIGN KEY (`carritos_id`)
    REFERENCES `dulceria`.`carritos` (`id`),
  CONSTRAINT `fk_ventas_medios_de_pago1`
    FOREIGN KEY (`medios_de_pago_id`)
    REFERENCES `dulceria`.`medios_de_pago` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_ventas_medios_de_pago1_idx` ON `dulceria`.`ventas` (`medios_de_pago_id` ASC) VISIBLE;

CREATE INDEX `fk_ventas_carritos1_idx` ON `dulceria`.`ventas` (`carritos_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
