@startuml Get Detalle Carrito By Code

participant Caller
participant Handler as handler
participant UseCase
participant DulcesProvider as dulcesp
participant CategoriasProvider as categoriasp
participant CarritoProvider as carritop
participant Query
participant DB

Caller -> handler ++: GET api/carritos/{id}
    handler -> handler: id, err := strconv.ParseUint(id)
    alt err != nil
        handler -> Caller: 400 Bad Request
    end
    handler -> UseCase ++: Execute(id)
        UseCase -> carritop ++: GetCarritoByCarritoID(id)
        carritop -> UseCase --: <carrito, err>
        alt err != nil
            UseCase -> handler: nil, err
            handler -> Caller: err
        end

        UseCase -> dulcesp ++: GetDulcesListByCarritoID(id)
        dulcesp -> UseCase --: <dulcesIDList, err>
        alt err != nil
            UseCase -> handler: nil, err
            handler -> Caller: err
        end

        UseCase -> UseCase: dulcesList []query.DetalleDulce

        loop dulceID := range dulcesIDList
            UseCase -> dulcesp ++: GetByID(dulceID)
            dulcesp -> UseCase --: <dulce, err>
            alt err != nil
                UseCase -> handler: nil, err
                handler -> Caller: err
            end
            UseCase -> categoriasp ++: GetCategoriasByDulceID(id)
            categoriasp -> UseCase --: <categoriasList, err>
            alt err != nil
                UseCase -> handler: nil, err
                handler -> Caller: err
            end
            UseCase -> Query ++: query.AddCategorias(categorias)
            Query -> Query: query.Categorias = categorias
            Query -> UseCase --: query

           UseCase -> UseCase: dulcesList = append(dulcesList, query)
        end

    UseCase -> handler -- : query.NewGetDetalleCarrito(carrito, dulcesList), nil

handler -> Caller --: <200 OK, query>     


    